/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.netology.pyas;

public class Main {
    private static final int OPERATORS_COUNT = 10;

    public static void main(String[] args) {
        ATS ats = new ATS();
        Thread atsThread = new Thread(ats::run);
        atsThread.start();
        for(int i = 0; i < OPERATORS_COUNT; ++i) {
            Operator operator = new Operator("Оператор"+ (i+1), ats);
            new Thread(operator::run).start();
        }
    }

}
